/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any
    tools {
        maven 'maven'
    }

    environment {
        ArtifactId  = readMavenPom().getArtifactId()
        Version     = readMavenPom().getVersion()
        Name        = readMavenPom().getName()
        GroupId     = readMavenPom().getGroupId()
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Pusblish Jar to Nexus Repository') {
            steps {
                script {
                    def mavenPom = readMavenPom file: 'pom.xml'
                    def nexusRepoName = mavenPom.version.endWith('SNAPSHOT') ? 'EpamDevOpsHW-SNAPSHOT' : 'EpamDevOpsHW-RELEASE'
                    nexusArtifactUploader artifacts:[
                        [
                            artifactId: "${ArtifactId}",
                            classifier: '',
                            file: "target/${ArtifactId}-${Version}.jar",
                            type: 'jar'
                        ]
                    ],
                    credentialsId: '51231d5b-eb83-4b91-8e8f-56020908d643',
                    groupId: "${GroupId}",
                    nexusUrl: '172.20.10.155:8081',
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    repository: "${NexusRepo}",
                    version: "${Version}"
                }
            }
        }
    }
}
